[versions]
agp = "8.13.1"
cardview = "1.0.0"
coilCompose = "2.7.0"
compiler = "5.0.5"
composeBom = "2025.12.01"
databindingRuntime = "8.13.1"
exoplayer = "2.19.1"
filekitDialogs = "0.12.0"
innertube = "1.0.1"
json = "20251224"
kotlin = "2.3.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxSerializationJson = "1.9.0"
activity = "1.12.2"
ksafe = "1.3.0"
ksafeCompose = "1.3.0"
ktor = "3.3.3"
materialVersion = "1.13.0"
media3Common = "1.9.0"
multiplatformMarkdownRendererM3 = "0.39.0"
navigationCompose = "2.9.6"
navigationSerialization = "2.7.7"
newpipeextractor = "0.24.4"
okhttp = "5.3.2"
recyclerview = "1.4.0"
media3Session = "1.9.0"
media3Exoplayer = "1.9.0"
roomCommonJvm = "2.8.4"
roomRuntimeAndroid = "2.8.4"
toasty = "1.5.2"
material3 = "1.5.0-alpha11"
ui = "1.10.0"
uiTooling = "1.10.0"
wavySlider = "2.2.0"
reorderable = "3.0.0"

[libraries]
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databindingRuntime" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Common" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Common" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-serialization = { module = "androidx.navigation:navigation-serialization", version.ref = "navigationSerialization" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCommonJvm" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCommonJvm" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekitDialogs" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
innertube = { module = "com.mewsic:innertube", version.ref = "innertube" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ksafe = { module = "eu.anifantakis:ksafe", version.ref = "ksafe" }
ksafe-compose = { module = "eu.anifantakis:ksafe-compose", version.ref = "ksafeCompose" }
ktor-client-core = {group = "io.ktor", name = "ktor-client-core", version.ref = "ktor"}
ktor-client-okhttp = {group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor"}
ktor-client-content-negotiation = {group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-encoding = {group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor"}
ktor-client-serialization = {group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor"}
ktor-serialization-json = {group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktor-serialization-kotlinx-xml = { group = "io.ktor", name = "ktor-serialization-kotlinx-xml", version.ref = "ktor" }
ktor-serialization-kotlinx-protobuf = { group = "io.ktor", name = "ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
brotli = { group = "org.brotli", name = "dec", version = "0.1.2" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatformMarkdownRendererM3" }
newpipeextractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version.ref = "newpipeextractor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Session" }
androidx-media3-exoplayer = {group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer"}
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
toasty = {group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty"}
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
wavy-slider = { module = "ir.mahozad.multiplatform:wavy-slider", version.ref = "wavySlider" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
