[versions]
agp = "8.9.1"
cardview = "1.0.0"
coilCompose = "2.7.0"
compiler = "5.0.4"
composeBom = "2025.09.01"
databindingRuntime = "8.9.1"
exoplayer = "2.19.1"
innertube = "1.0.1"
kotlin = "2.2.10"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.9.0"
kotlinx-serialization = "1.9.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.1.4"
ktor = "2.3.12"
materialVersion = "1.13.0"
media3Common = "1.8.0"
navigationCompose = "2.9.3"
# Align this version with navigationCompose
navigationSerialization = "2.7.7"
newpipeextractor = "0.24.4"
okhttp = "4.12.0"
recyclerview = "1.4.0"
media3Session = "1.7.1"
media3Exoplayer = "1.7.1"
roomCommonJvm = "2.7.1"
roomRuntimeAndroid = "2.7.1"
toasty = "1.5.2"
material3 = "1.3.2"
ui = "1.9.0"
uiTooling = "1.9.0"

[libraries]
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
androidx-databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databindingRuntime" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Common" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Common" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-serialization = { module = "androidx.navigation:navigation-serialization", version.ref = "navigationSerialization" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCommonJvm" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCommonJvm" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
innertube = { module = "com.mewsic:innertube", version.ref = "innertube" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
brotli = { group = "org.brotli", name = "dec", version = "0.1.2" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
newpipeextractor = { module = "com.github.teamnewpipe:NewPipeExtractor", version.ref = "newpipeextractor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Session" }
androidx-media3-exoplayer = {group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer"}
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
toasty = {group = "com.github.GrenderG", name = "Toasty", version.ref = "toasty"}
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
